### PR TITLE
Support new Orbitty carrier board

### PR DESCRIPTION
**Pull request by pastawoua**
Add support for the [Orbitty](http://connecttech.com/product/orbitty-carrier-for-nvidia-jetson-tx2-tx1) carrier board from Connect Tech.

- Added new machine configuration
- Added custom dtb

### CODE REVIEW

**Comment by telphan** [comment]
@pastawoua have you managed to test this, on a real board?

**Comment by pastawoua** [comment]
@telphan I did initially by swapping the skx2 dtb and it worked.

I've just tested this morning with this version including an extra machine and it failed complaining it can't find the firmware. I must have missed something, I'm not familiar on how the `linux-tegra_%.bbappend` file is meant to be structured, can you spot anything standing out?

**Comment by telphan** [comment]
@pastawoua what is the error you are facing?

**Comment by telphan** [comment]
This PR is missing one key bit (the DTB), now I have tested the Obitty Carrier board (http://connecttech.com/product/orbitty-carrier-for-nvidia-jetson-tx2-tx1/) with our default image (that uses the devkit DTB) and from my perspective everything seems to work. 
I will close this PR because of the above reason. If anyway find issues with our image and this carrier board you are welcome to open an issue.

**Pull request closed without merging**
